Add files via upload

diff --git a/genomegit b/genomegit
--- a/genomegit
+++ b/genomegit
@@ -458,11 +458,16 @@ elif [ "$1" = "diff" ]; then
 		threads=1
 		message=0
 		merge=0
+		aligner=2
+		percent_identity=95
+		kmer=16
+		segLength=5000
+		inversions=0
 		#Loop through the arguments
 		for WORD; do
 			case $WORD in
 				#If the current argument is the optional number of threads
-				--threads=*)
+				--t|--threads=*)
 					#Determine the number of threads selected
 					threads=${1#*=}
 					#Determine if the threads is a valid input, otherwise default it back to 1
@@ -485,6 +490,56 @@ elif [ "$1" = "diff" ]; then
 					#Shift arguments
 					shift
 					;;
+				--a=*|--aligner=*)
+					#Determine which aligner was chosen
+					aligner=${1#*=}
+					if ! [[ "$aligner" =~ ^[1-2]+$ ]] || ! [ "$aligner" -ge 1 ]; then
+						echo "Invalid aligner selection, defaulting it to nucmer."
+						aligner=2
+					fi
+					#Shift the arguments (jump to the next)
+					shift
+					;;
+				--pi=*)
+					#Determine which aligner was chosen
+					percent_identity=${1#*=}
+					if ! [[ "$percent_identity" =~ ^[0-9]+$ ]] || ! [ "$percent_identity" -ge 1 ]; then
+						echo "Invalid percent identity value, defaulting it to 95."
+						percent_identity=95
+					fi
+					#Shift the arguments (jump to the next)
+					shift
+					;;
+				--k=*|--kmer=*)
+					#Determine which aligner was chosen
+					kmer=${1#*=}
+					if ! [[ "$kmer" =~ ^[0-9]+$ ]] || ! [ "$kmer" -ge 1 ]; then
+						echo "Invalid k-mer selected, defaulting it to 16."
+						kmer=16
+					fi
+					#Shift the arguments (jump to the next)
+					shift
+					;;
+				--s=*|--segLength=*)
+					#Determine which aligner was chosen
+					segLength=${1#*=}
+					if ! [[ "$segLength" =~ ^[0-9]+$ ]] || ! [ "$segLength" -ge 1 ]; then
+						echo "Invalid segment length selected, defaulting it to 5000."
+						segLength=5000
+					fi
+						#Shift the arguments (jump to the next)
+					shift
+					;;
+				--inv=*|--inversions=*)
+					#Determine which aligner was chosen
+					inversions=${1#*=}
+					if ! [[ "$inversions" =~ ^[0-9]+$ ]] || ! [ "$inversions" -ge 1 ]; then
+						echo "Invalid inversions setting selected, defaulting it to forwards flag."
+						inversions=0
+					fi
+						#Shift the arguments (jump to the next)
+					shift
+					;;
 			esac
 		done
 		#If the user provided a message, determine the commit hash associated to them (in case of multiple ones, the first one will be selected)
@@ -499,7 +554,8 @@ elif [ "$1" = "diff" ]; then
 			commit_B=$2
 		fi
 		#Run the summary. Arguments: commitA commitB threads merge
-		python $source/review.py $commit_A $commit_B $threads $merge
+		python $source/review.py $commit_A $commit_B $threads $merge "$aligner"\
+		"$percent_identity" "$kmer" "$segLength" "$inversions"
 	#Inform the user ther is no .gnmgit repo
 	else
 		echo "No genomegit repository detected. Use genomegit init to initiate one."
